# Generated by Django 3.2.9 on 2021-12-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_auto_20211210_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('fabricante', models.EmailField(max_length=40)),
                ('plataforma', models.CharField(max_length=40)),
                ('faixaetaria', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
