# Generated by Django 3.2.9 on 2021-12-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0005_auto_20211210_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='fabricante',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='faixaetaria',
            field=models.IntegerField(verbose_name='Faixa Etária'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Alugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locadora.cliente')),
                ('codigo_jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locadora.jogo')),
            ],
        ),
    ]
