# Generated by Django 3.2.9 on 2021-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0006_auto_20211213_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='alugar',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alugar',
            name='total',
            field=models.FloatField(default=1, verbose_name='Total a pagar'),
            preserve_default=False,
        ),
    ]
